stages:
  - prepare
  - test
  - build
  - deploy

prepare:
  image: node:18
  stage: prepare
  script:
    - npm install
  cache:
    untracked: true
    paths:
      - node_modules
  artifacts:
    expire_in: 1 hour
    when: always
    untracked: true
    paths:
      - node_modules
      - package-lock.json

lint:
  image: node:18
  stage: test
  dependencies:
    - prepare
  script:
    - npm run lint

build:
  image: node:18
  stage: test
  dependencies:
    - prepare
  script:
    - npm run build

build container:
  stage: build
  image: atnartur/docker:latest
  only:
    - dev
  script:
    - docker-compose -f compose.yml build
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker-compose -f compose.yml push

deploy dev:
  stage: deploy
  image: atnartur/docker:latest
  only:
    - dev
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker-compose -f compose.yml pull
    - docker-compose -f compose.yml up -d --remove-orphans
