stages:
  - test
  - build
  - deploy

lint:
  image: node:18
  stage: test
  tags:
    - docker
  script:
    - npm install
    - npm run lint

build container:
  stage: build
  image: atnartur/docker:latest
  tags:
    - docker
  script:
    - docker-compose -f compose.yml build
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker-compose -f compose.yml push

deploy dev:
  stage: deploy
  image: atnartur/docker:latest
  only:
    - dev
  tags:
    - docker-compose
    - dev
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker-compose -f compose.yml pull
    - docker-compose -f compose.yml up -d --remove-orphans

deploy prod:
  stage: deploy
  image: atnartur/docker:latest
  only:
    - dev
  tags:
    - docker-compose
    - dev
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker-compose -f compose.yml pull
    - docker-compose -f compose.yml up -d --remove-orphans
