stages:
  - prepare
  - test
  - build
  - deploy

prepare:
  image: node:16
  stage: prepare
  script:
    - npm install
  cache:
    untracked: true
    paths:
      - node_modules
  artifacts:
    expire_in: 1 hour
    when: always
    untracked: true
    paths:
      - node_modules
      - package-lock.json

lint:
  image: node:16
  stage: test
  dependencies:
    - prepare
  script:
    - npm run lint

build:
  image: node:16
  stage: test
  dependencies:
    - prepare
  script:
    - npm run build

Build dev:
  stage: build
  image: atnartur/docker:latest
  only:
    - main
  script:
    - docker-compose -f docker-compose.dev.yml build
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker-compose -f docker-compose.dev.yml push

Deploy dev:
  stage: deploy
  image: atnartur/docker:latest
  only:
    - dev
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker-compose -f docker-compose.dev.yml pull
    - docker-compose -f docker-compose.dev.yml up -d
