version: '3.6'

services:
  frontend-prod:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
      args:
        VITE_API_URL: https://api.clavis.the-o.co
    image: frontend
    restart: unless-stopped
    ports:
      - '3000:80'
    expose:
      - '80'
